"""Submit EVIDENCE_PACK_R18_WORKSPACE_CLEANUP.zip to ChatGPT via CDP."""
import asyncio
from playwright.async_api import async_playwright

ZIP_PATH = r"D:\agent-acceptance\_evidence\EVIDENCE_PACK_R18_WORKSPACE_CLEANUP.zip"
TARGET_URL = "https://chatgpt.com/c/6a297f76-3e7c-83a5-a0e5-b4413d923c7e"
CDP_URL = "http://localhost:9222"

SUBMISSION_MSG = """R18 Workspace Cleanup Evidence Pack - All Non-Blocking Follow-Up Items Addressed

## EVIDENCE_PACK_R18_WORKSPACE_CLEANUP.zip (10 files, 608 KB)
## Commit: 104ac8b1 (44 files changed)

### Items Addressed (from GPT R18 FOLLOWUP FINAL verdict remaining_non_blocking_followup)

1. **PROJECT_REGISTRY.json reconciliation**: COMMITTED
   - dev-frame-opencode added (binding_status: active)
   - total_projects: 10 -> 11
   - updated_at: 2026-06-11T01:35:26Z

2. **Session artifact scripts**: COMMITTED (5 scripts)
   - _build_r18_followup_final.py
   - _capture_followup_reply.py
   - _submit_r18_final.py
   - _submit_r18_followup.py
   - _submit_r18_followup_v2.py

3. **NEG-009 files**: PRESERVED (17 files remain deferred per deny_paths)

4. **NUL artifact**: REMOVED via `rm -- NUL` in git bash (Windows reserved device name)

5. **Evidence packs**: COMMITTED
   - EVIDENCE_PACK_R18_FOLLOWUP.zip (9 files, 98 KB)
   - EVIDENCE_PACK_R18_FOLLOWUP_FINAL.zip (15 files, 193 KB)
   - R18-followup-cleanup/ directory (10 files)
   - R18-FOLLOWUP-FINAL/ directory (15 files)

### Additional Changes
- hooks/sealed-files-manifest.json: auto-regenerated by SADP pre-commit hook
- tests/test_router_10_project_stress.py: EXPECTED_PROJECTS 10->11, ACTIVE_PROJECTS includes dev-frame-opencode
- final-report.md naming fix: sadp-audit-output-bc974d2f.txt -> sadp-audit-raw.txt

### SADP Hook Output
- [1/3] Manifest regeneration: PASS
- [2/3] SADP audit: PASS (44 files, all covered by TaskSpec write_sets)
- [3/3] Governance advisory: PASS (ProtectedPaths, Secrets, BatchReferences)
- ai_guard: 0 errors, 1 warning (hooks/sealed-files-manifest.json RESTRICTED)
- 2 secret-scan-output.txt files unstaged (deny list - mock patterns)

### Verification
- Tests: 1038 passed, 0 failed, 21 warnings
- ai_guard scope: 0 violations
- deny_path: 0 violations"""

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.connect_over_cdp(CDP_URL)
        ctx = browser.contexts[0]
        
        target_page = None
        for page in ctx.pages:
            if "6a297f76-3e7c-83a5-a0e5-b4413d923c7e" in page.url:
                target_page = page
                break
        
        if not target_page:
            print("Opening target page...")
            page = ctx.pages[0] if ctx.pages else await ctx.new_page()
            await page.goto(TARGET_URL, wait_until="networkidle", timeout=30000)
            target_page = page
        
        print(f"Page: {target_page.url}")
        await target_page.wait_for_timeout(3000)
        
        user_msgs_before = await target_page.locator('div[data-message-author-role="user"]').count()
        print(f"User messages before: {user_msgs_before}")
        
        # Upload ZIP
        print("Uploading ZIP...")
        file_input = target_page.locator('#upload-files')
        await file_input.set_input_files(ZIP_PATH)
        await target_page.wait_for_timeout(3000)
        print("File uploaded.")
        
        # Type message via clipboard
        print("Typing message...")
        editor = target_page.locator('#prompt-textarea, div[contenteditable="true"]').last
        await editor.click()
        await editor.fill("")
        await target_page.wait_for_timeout(500)
        
        await target_page.evaluate(f"""
            async () => {{
                const text = {repr(SUBMISSION_MSG)};
                await navigator.clipboard.writeText(text);
            }}
        """)
        await target_page.wait_for_timeout(500)
        await editor.press("Control+v")
        await target_page.wait_for_timeout(2000)
        
        # Click send
        print("Sending...")
        send_btn = target_page.locator('button[data-testid="send-button"]')
        if await send_btn.count() > 0:
            await send_btn.first.click()
            print("Clicked send button.")
        else:
            await editor.press("Enter")
            print("Pressed Enter.")
        
        await target_page.wait_for_timeout(5000)
        
        user_msgs_after = await target_page.locator('div[data-message-author-role="user"]').count()
        print(f"User messages after: {user_msgs_after}")
        
        if user_msgs_after > user_msgs_before:
            print(f"SUCCESS: Message sent ({user_msgs_before} -> {user_msgs_after})")
        else:
            print(f"WARNING: Message count unchanged")
        
        # Wait for reply
        print("Waiting for GPT response (180s)...")
        await target_page.wait_for_timeout(180000)
        
        assistant_msgs = target_page.locator('div[data-message-author-role="assistant"]')
        count = await assistant_msgs.count()
        if count > 0:
            last_reply = await assistant_msgs.last.inner_text()
            print(f"\n=== GPT REPLY ({len(last_reply)} chars) ===")
            print(last_reply[:3000])
            
            out_path = r"D:\agent-acceptance\_evidence\R18-WORKSPACE-CLEANUP\gpt_reply.txt"
            os.makedirs(os.path.dirname(out_path), exist_ok=True)
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(last_reply)
            print(f"\nSaved to {out_path}")

import os
asyncio.run(main())
