"""Submit EVIDENCE-CAPTURE-STANDARD-A1 to ChatGPT via CDP."""
import asyncio, os
from playwright.async_api import async_playwright

ZIP_PATH = r"D:\agent-acceptance\_evidence\EVIDENCE_PACK_EVIDENCE_CAPTURE_STANDARD_A1.zip"
TARGET_URL = "https://chatgpt.com/c/6a297f76-3e7c-83a5-a0e5-b4413d923c7e"
CDP_URL = "http://localhost:9222"

MSG = """EVIDENCE-CAPTURE-STANDARD-A1 — Reusable Builder + Hook Output Persistence

ZIP: EVIDENCE_PACK_EVIDENCE_CAPTURE_STANDARD_A1.zip (16 files, 46 KB)
SHA256: ca6e7c9a421f10f87b4bf18e46da06d811e0e56e5b5e267aaf3ebac2a4b3f06e

Commit: 20a4aa2 (7 files, SADP hook v2.1.0 PASS)
Built with: scripts/build_evidence_pack.py (the NEW reusable builder itself)

=== Deliverables ===

1. scripts/build_evidence_pack.py (reusable parameterized builder)
   - CLI: --task-id, --commits, --base, --out, --zip, --hook-log
   - Generates 16 evidence files in single pass
   - Internal consistency guarantee (single git-status snapshot)
   - Replaces 39 one-off _build_*.py scripts

2. hooks/pre-commit.governance.ps1 v2.1.0 (output persistence)
   - Stage 2: captures sadp-audit + ai_guard to timestamped files
   - Stage 3: captures Test-Governance output
   - Combined JSON at _evidence/hook-output/latest.json
   - Additive only — existing 3-stage logic preserved

3. schemas/agent-runtime/evidence-capture.schema.json
   - JSON Schema for hook-output/latest.json

4. docs/agent-runtime/evidence-capture-workflow.md (388 lines)
   - Phase A: automatic hook output persistence
   - Phase B: evidence pack building with reusable builder
   - Migration guide for one-off scripts

=== Post-Commit State ===
- Modified tracked: 0
- Untracked: 34 (17 NEG-009 + 5 secret-scan + 12 session artifacts)
- Tests: 1038 passed, 0 failed, 21 warnings
- Hook output captured to _evidence/hook-output/ (NEW!)

=== Evidence built with the new builder itself ===
This evidence pack was generated by scripts/build_evidence_pack.py
-- the reusable builder created as part of this task.
This is the first real-world test of the new tool."""

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.connect_over_cdp(CDP_URL)
        ctx = browser.contexts[0]
        target_page = None
        for page in ctx.pages:
            if "6a297f76-3e7c-83a5-a0e5-b4413d923c7e" in page.url:
                target_page = page
                break
        if not target_page:
            print("Page not found, navigating...")
            page = ctx.pages[0]
            await page.goto(TARGET_URL, wait_until="networkidle", timeout=30000)
            target_page = page

        print(f"Page: {target_page.url}")
        await target_page.wait_for_timeout(3000)
        ub = await target_page.locator('div[data-message-author-role="user"]').count()
        print(f"User msgs before: {ub}")

        print("Uploading ZIP...")
        await target_page.locator('#upload-files').set_input_files(ZIP_PATH)
        await target_page.wait_for_timeout(5000)

        modal = target_page.locator('#modal-duplicate-file')
        if await modal.count() > 0 and await modal.is_visible():
            pb = modal.locator('button.btn-primary')
            if await pb.count() > 0:
                await pb.first.click(force=True)
            else:
                btns = modal.locator('button')
                if await btns.count() > 0:
                    await btns.last.click(force=True)
            await target_page.wait_for_timeout(2000)

        await target_page.evaluate("() => { const e = document.querySelector('#prompt-textarea'); if(e) e.focus(); }")
        await target_page.wait_for_timeout(500)
        await target_page.keyboard.type(MSG, delay=2)
        await target_page.wait_for_timeout(2000)

        send_btn = target_page.locator('button[data-testid="send-button"]')
        disabled = await send_btn.first.get_attribute("disabled")
        print(f"Send disabled: {repr(disabled)}")
        if disabled is None:
            await send_btn.first.click()
        else:
            await target_page.evaluate("""() => {
                const e = document.querySelector('#prompt-textarea');
                if(e) e.dispatchEvent(new InputEvent('input', {bubbles:true, inputType:'insertText'}));
            }""")
            await target_page.wait_for_timeout(1000)
            d2 = await send_btn.first.get_attribute("disabled")
            if d2 is None:
                await send_btn.first.click()
            else:
                await send_btn.first.click(force=True)

        await target_page.wait_for_timeout(8000)
        ua = await target_page.locator('div[data-message-author-role="user"]').count()
        print(f"User msgs after: {ua}")
        if ua <= ub:
            print("Count unchanged, trying Enter...")
            await target_page.keyboard.press("Enter")
            await target_page.wait_for_timeout(5000)
            ua2 = await target_page.locator('div[data-message-author-role="user"]').count()
            if ua2 > ub:
                print(f"SUCCESS after Enter: {ub} -> {ua2}")
            else:
                print("FAILED to send")
                return
        else:
            print(f"SUCCESS: {ub} -> {ua}")

        print("Waiting for GPT (180s)...")
        await target_page.wait_for_timeout(180000)

        ams = target_page.locator('div[data-message-author-role="assistant"]')
        cnt = await ams.count()
        if cnt > 0:
            reply = await ams.last.inner_text()
            print(f"\n=== GPT REPLY ({len(reply)} chars) ===")
            print(reply[:10000])
            op = r"D:\agent-acceptance\_evidence\EVIDENCE-CAPTURE-STANDARD-A1\gpt_reply_ecs.txt"
            os.makedirs(os.path.dirname(op), exist_ok=True)
            with open(op, "w", encoding="utf-8") as f:
                f.write(reply)
            print(f"\nSaved: {op}")

asyncio.run(main())
