# AUDIT-ONLY DRAFT
# Not registered - Not blocking - No mutation - No secret access
#
# pre-edit.audit.draft.ps1
# Runs before a file edit operation (conceptual hook, not actually registered).
# Outputs audit recommendations to stdout. Always exits 0.
#
# Usage (conceptual): Receive file path and edit info on stdin, output audit to stdout.

param(
    [Parameter(ValueFromPipeline = $true)]
    [string]$EditInfo = ""
)

$AUDIT_HEADER = @"

========================================
 PRE-EDIT AUDIT (Draft - Not Registered)
========================================
"@

Write-Output $AUDIT_HEADER

if (-not $EditInfo) {
    Write-Output "[AUDIT] No edit info provided. Suggest: pass file path and edit type."
    Write-Output "[AUDIT] STATUS: INCOMPLETE_INPUT"
    exit 0
}

# Parse file path
$filePath = ""
if ($EditInfo -match '"file_path"\s*:\s*"([^"]+)"') { $filePath = $Matches[1] }
if (-not $filePath -and $EditInfo -match '"path"\s*:\s*"([^"]+)"')  { $filePath = $Matches[1] }

Write-Output "[AUDIT] Target file: $filePath"

# P0: Reject edits to secret files
$secretPatterns = @("\.env$", "\.key$", "\.pem$", "token", "credential", "id_rsa", "id_ed25519")
foreach ($pattern in $secretPatterns) {
    if ($filePath -match $pattern) {
        Write-Output "[AUDIT] HARD STOP: File matches secret pattern: '$pattern'"
        Write-Output "[AUDIT]   Do NOT edit this file. Report to reviewer."
        Write-Output "[AUDIT] STATUS: BLOCKED_SECRET_PATTERN"
        exit 0
    }
}

# P1: Check write scope - Phase 0-5 approved directories
$approvedScopes = @(
    [regex]::Escape("D:\agent-acceptance\docs\agent-runtime\"),
    [regex]::Escape("D:\agent-acceptance\rules\"),
    [regex]::Escape("D:\agent-acceptance\hooks\"),
    [regex]::Escape("D:\agent-acceptance\skills-inbox\")
)

$inApprovedScope = $false
foreach ($scope in $approvedScopes) {
    if ($filePath -match "^$scope") {
        $inApprovedScope = $true
        break
    }
}

# P1: Check against dirty baseline files
$dirtyBaseline = @(
    "README.md",
    "agent-workqueue\QUEUE_INDEX.md",
    "agent-workqueue\cleanup-dryrun.queue.json",
    "agent-workqueue\docs-quality.queue.json",
    "agent-workqueue\local-quality.queue.json",
    "agent-workqueue\recovery-regression.queue.json",
    "agent-workqueue\release-readiness.queue.json",
    "docs\FLOW_CATALOG.md",
    "docs\NEXT_STAGE_BACKLOG.md",
    "docs\RUNBOOK.md",
    "scripts\Run-WorkQueue.ps1",
    "scripts\Test-WorkQueue.ps1",
    "scripts\examples\batch-docs-quality.json"
)

$isDirtyBaseline = $false
foreach ($dirty in $dirtyBaseline) {
    if ($filePath -match [regex]::Escape($dirty)) {
        $isDirtyBaseline = $true
        break
    }
}

if ($isDirtyBaseline) {
    Write-Output "[AUDIT] WARNING: Target file is in dirty baseline (13 modified files)."
    Write-Output "[AUDIT]   Phase 0-5 rule: do NOT modify dirty baseline files."
    Write-Output "[AUDIT]   Recommend: skip this edit unless explicitly approved in batch plan."
    Write-Output "[AUDIT] STATUS: WARNING_DIRTY_BASELINE"
    exit 0
}

if (-not $inApprovedScope) {
    Write-Output "[AUDIT] WARNING: Target file is outside Phase 0-5 approved write scope."
    Write-Output "[AUDIT]   Approved scopes: docs/agent-runtime/, rules/, hooks/, skills-inbox/"
    Write-Output "[AUDIT]   Recommend: verify this edit is in the current batch plan."
    Write-Output "[AUDIT] STATUS: WARNING_OUTSIDE_SCOPE"
    exit 0
}

# P2: Check for forbidden directories
$forbiddenDirs = @("\.claude", "\.codegraph", "\.git", "node_modules", "__pycache__")
foreach ($dir in $forbiddenDirs) {
    if ($filePath -match $dir) {
        Write-Output "[AUDIT] WARNING: Target file is in forbidden directory: '$dir'"
        Write-Output "[AUDIT] STATUS: WARNING_FORBIDDEN_DIR"
        exit 0
    }
}

Write-Output "[AUDIT] File is in approved scope. Proceed with edit."
Write-Output "[AUDIT] STATUS: PASS"
exit 0
