# ACTIVE HOOK — Governance Gate
# Registered - Blocking on hard violations - No mutation - No secret access
#
# pre-edit.audit.draft.ps1
# Runs before Write/Edit tool calls. Blocks edits to memory, sealed files, and secrets.
# Exit 0: allowed. Exit 1: BLOCKED (hard violation).
#
# Usage: Hook runs with file_path from tool call context.

param(
    [Parameter(ValueFromPipeline = $true)]
    [string]$EditInfo = ""
)

$AUDIT_HEADER = @"

========================================
 PRE-EDIT AUDIT (Draft - Not Registered)
========================================
"@

Write-Output $AUDIT_HEADER

if (-not $EditInfo) {
    Write-Output "[AUDIT] No edit info provided. Suggest: pass file path and edit type."
    Write-Output "[AUDIT] STATUS: INCOMPLETE_INPUT"
    exit 0
}

# Parse file path
$filePath = ""
if ($EditInfo -match '"file_path"\s*:\s*"([^"]+)"') { $filePath = $Matches[1] }
if (-not $filePath -and $EditInfo -match '"path"\s*:\s*"([^"]+)"')  { $filePath = $Matches[1] }

Write-Output "[AUDIT] Target file: $filePath"

# P0: Block edits to memory directories — HARD STOP
$memoryPaths = @(
    "C:\Users\RD\.claude\projects\D--agent-acceptance\memory\",
    "C:\Users\RD\.claude\memory\"
)
foreach ($memPath in $memoryPaths) {
    $memPattern = [regex]::Escape($memPath)
    if ($filePath -match $memPattern) {
        Write-Output "[AUDIT] HARD STOP: Target is in RD2100 memory directory."
        Write-Output "[AUDIT]   Handoff 'Do Not write RD2100 memory' — BLOCKED."
        Write-Output "[AUDIT] STATUS: BLOCKED_MEMORY_WRITE"
        exit 1
    }
}

# P0: Block edits to sealed files — HARD STOP
$sealedFiles = @(
    "resource-integration-handoff.md",
    "resource-integration-final-audit.md",
    "resource-integration-plan.md",
    "resource-integration-status-index.md",
    "resource-registry.md",
    "resource-risk-matrix.md",
    "capability-routing-handoff.md",
    "capability-routing-final-audit.md",
    "capability-inventory.md",
    "task-capability-routing-matrix.md",
    "operating-model.md",
    "integration-contracts.md",
    "tool-policy.md",
    "memory-architecture.md",
    "skill-trigger-matrix.md",
    "verification-gates.md",
    "runtime-invariants.md",
    "stride-threat-model.md",
    "fmea-risk-analysis.md",
    "phase-6b-handoff.md",
    "phase-6b-source-lock-plan.md"
)
foreach ($sealed in $sealedFiles) {
    $pattern = [regex]::Escape($sealed)
    if ($filePath -match $pattern) {
        Write-Output "[AUDIT] HARD STOP: Target file is SEALED."
        Write-Output "[AUDIT]   '$sealed' is in sealed-files-manifest.json."
        Write-Output "[AUDIT]   To unseal: remove from manifest with human approval."
        Write-Output "[AUDIT] STATUS: BLOCKED_SEALED_FILE"
        exit 1
    }
}

# P0: Reject edits to secret files
$secretPatterns = @("\.env$", "\.key$", "\.pem$", "token", "credential", "id_rsa", "id_ed25519")
foreach ($pattern in $secretPatterns) {
    if ($filePath -match $pattern) {
        Write-Output "[AUDIT] HARD STOP: File matches secret pattern: '$pattern'"
        Write-Output "[AUDIT]   Do NOT edit this file. Report to reviewer."
        Write-Output "[AUDIT] STATUS: BLOCKED_SECRET_PATTERN"
        exit 1
    }
}

# P1: Check write scope - Phase 0-5 approved directories
$approvedScopes = @(
    [regex]::Escape("D:\agent-acceptance\docs\agent-runtime\"),
    [regex]::Escape("D:\agent-acceptance\rules\"),
    [regex]::Escape("D:\agent-acceptance\hooks\"),
    [regex]::Escape("D:\agent-acceptance\skills-inbox\")
)

$inApprovedScope = $false
foreach ($scope in $approvedScopes) {
    if ($filePath -match "^$scope") {
        $inApprovedScope = $true
        break
    }
}

# P1: Check against dirty baseline files
$dirtyBaseline = @(
    "README.md",
    "agent-workqueue\QUEUE_INDEX.md",
    "agent-workqueue\cleanup-dryrun.queue.json",
    "agent-workqueue\docs-quality.queue.json",
    "agent-workqueue\local-quality.queue.json",
    "agent-workqueue\recovery-regression.queue.json",
    "agent-workqueue\release-readiness.queue.json",
    "docs\FLOW_CATALOG.md",
    "docs\NEXT_STAGE_BACKLOG.md",
    "docs\RUNBOOK.md",
    "scripts\Run-WorkQueue.ps1",
    "scripts\Test-WorkQueue.ps1",
    "scripts\examples\batch-docs-quality.json"
)

$isDirtyBaseline = $false
foreach ($dirty in $dirtyBaseline) {
    if ($filePath -match [regex]::Escape($dirty)) {
        $isDirtyBaseline = $true
        break
    }
}

if ($isDirtyBaseline) {
    Write-Output "[AUDIT] WARNING: Target file is in dirty baseline (13 modified files)."
    Write-Output "[AUDIT]   Phase 0-5 rule: do NOT modify dirty baseline files."
    Write-Output "[AUDIT]   Recommend: skip this edit unless explicitly approved in batch plan."
    Write-Output "[AUDIT] STATUS: WARNING_DIRTY_BASELINE"
    exit 0
}

if (-not $inApprovedScope) {
    Write-Output "[AUDIT] WARNING: Target file is outside Phase 0-5 approved write scope."
    Write-Output "[AUDIT]   Approved scopes: docs/agent-runtime/, rules/, hooks/, skills-inbox/"
    Write-Output "[AUDIT]   Recommend: verify this edit is in the current batch plan."
    Write-Output "[AUDIT] STATUS: WARNING_OUTSIDE_SCOPE"
    exit 0
}

# P2: Check for forbidden directories
$forbiddenDirs = @("\.claude", "\.codegraph", "\.git", "node_modules", "__pycache__")
foreach ($dir in $forbiddenDirs) {
    if ($filePath -match $dir) {
        Write-Output "[AUDIT] WARNING: Target file is in forbidden directory: '$dir'"
        Write-Output "[AUDIT] STATUS: WARNING_FORBIDDEN_DIR"
        exit 0
    }
}

Write-Output "[AUDIT] File is in approved scope. Proceed with edit."
Write-Output "[AUDIT] STATUS: PASS"
exit 0
