# New-SessionLedger.ps1
# Auto-generates session_ledger.yaml from git diff and session context.
# Eliminates manual ledger filling ¡ª no Plan Agent honesty dependency.
#
# Usage: .\New-SessionLedger.ps1 -SessionId "ses-001" -Objective "P0 structural sync"
# Output: session_ledger.yaml (stdout or file)

param(
    [Parameter(Mandatory=$true)]
    [string]$SessionId,

    [Parameter(Mandatory=$true)]
    [string]$Objective,

    [string]$OutputPath,

    [string]$ProjectRoot = ".",

    [string[]]$ProtectedFiles = @("AGENTS.md", "CLAUDE.md", "rules/core.md", "rules/security.md",
        "docs/agent-runtime/sub-agent-dispatch-protocol.md",
        "docs/agent-runtime/capability-inventory.md",
        "docs/agent-runtime/lessons-learned.md",
        "docs/agent-runtime/session-ledger.schema.md",
        "docs/agent-runtime/audit-record.schema.md")
)

$ErrorActionPreference = "Stop"
Push-Location $ProjectRoot

try {
    # Collect git diff
    $diffStat = cmd /c "git -c core.safecrlf=false diff --stat HEAD" 2>$null
    $diffNumStat = cmd /c "git -c core.safecrlf=false diff --numstat HEAD" 2>$null
    $untracked = cmd /c "git -c core.safecrlf=false ls-files --others --exclude-standard" 2>$null

    $changedFiles = @()
    $governanceFilesTouched = $false
    $protectedFilesTouched = $false
    $touchedProtected = @()
    $writeCount = 0
    $newCount = 0

    # Parse modified files from numstat
    if ($diffNumStat) {
        $diffNumStat -split "`n" | ForEach-Object {
            $parts = $_ -split "`t"
            if ($parts.Count -ge 3) {
                $added = $parts[0]
                $removed = $parts[1]
                $path = $parts[2]

                $isGovernance = $path -match "^rules/|^docs/agent-runtime/(sub-agent-dispatch|capability-inventory|lessons-learned|session-ledger|audit-record|governance-manifest)"
                $isProtected = $ProtectedFiles -contains $path

                if ($isGovernance) { $governanceFilesTouched = $true }
                if ($isProtected) {
                    $protectedFilesTouched = $true
                    $touchedProtected += $path
                }

                $changedFiles += @{
                    path = $path
                    change_type = "modified"
                    governance_file = $isGovernance
                    protected_file = $isProtected
                }
                $writeCount++
            }
        }
    }

    # Parse untracked (new) files
    if ($untracked) {
        $untracked -split "`n" | ForEach-Object {
            $path = $_.Trim()
            if ($path -and $path -ne "") {
                $isGovernance = $path -match "^rules/|^docs/agent-runtime/(sub-agent-dispatch|capability-inventory|lessons-learned|session-ledger|audit-record|governance-manifest)"
                $isProtected = $ProtectedFiles -contains $path

                if ($isGovernance) { $governanceFilesTouched = $true }
                if ($isProtected) {
                    $protectedFilesTouched = $true
                    $touchedProtected += $path
                }

                $changedFiles += @{
                    path = $path
                    change_type = "new"
                    governance_file = $isGovernance
                    protected_file = $isProtected
                }
                $writeCount++
                $newCount++
            }
        }
    }

    # Determine SADP trigger
    $sadpRequired = $false
    $triggerReasons = @()
    if ($writeCount -ge 3) { $sadpRequired = $true; $triggerReasons += "3+ files modified ($writeCount)" }
    if ($governanceFilesTouched) { $sadpRequired = $true; $triggerReasons += "governance files touched" }
    if ($protectedFilesTouched) { $sadpRequired = $true; $triggerReasons += "protected files touched" }

    $auditRequired = $writeCount -gt 0
    if ($protectedFilesTouched -or $governanceFilesTouched) { $auditRequired = $true }

    # Build ledger YAML
    $timestamp = (Get-Date).ToString("yyyy-MM-ddTHH:mm:sszzz")
    $yaml = @"
# Session Ledger ¡ª Auto-generated by New-SessionLedger.ps1
# DO NOT manually edit. Plan Agent cannot set audit_status to "passed".
session_ledger:
  session_id: "$SessionId"
  objective: "$Objective"
  started_at: "$timestamp"
  completed_at: "$timestamp"

  changed_files:
"@

    foreach ($f in $changedFiles) {
            $yaml += "    - path: `"$($f.path)`"`n"
        $yaml += "      change_type: $($f.change_type)`n"
        $yaml += "      governance_file: $($f.governance_file.ToString().ToLower())`n"
        $yaml += "      protected_file: $($f.protected_file.ToString().ToLower())`n"
    }

    if ($changedFiles.Count -eq 0) {
        $yaml += "    []  # No changes detected`n"
    }

    $yaml += @"

  protected_files_touched: $($protectedFilesTouched.ToString().ToLower())
  protected_files_list:
"@
    if ($touchedProtected.Count -gt 0) {
        foreach ($p in $touchedProtected) { $yaml += "    - `"$p`"`n" }
    } else {
        $yaml += "    []`n"
    }

    $yaml += @"

  taskspecs_created: []  # To be filled by Plan Agent
  execution_reports_created: []  # To be filled by Plan Agent

  cumulative_write_set: $writeCount
  cumulative_new_artifacts: $newCount
  cumulative_protected_touches: $($touchedProtected.Count)
  cumulative_task_count: 1

  sadp_required: $($sadpRequired.ToString().ToLower())
  sadp_trigger_reason:
"@
    if ($triggerReasons.Count -gt 0) {
        foreach ($r in $triggerReasons) { $yaml += "    - `"$r`"`n" }
    } else {
        $yaml += "    []`n"
    }

    $yaml += @"

  audit_required: $($auditRequired.ToString().ToLower())
  audit_status: pending  # ONLY Plan Auditor may change this

  plan_agent_signoff: ""
  plan_agent_cannot_self_audit: true
"@

    if ($OutputPath) {
        $yaml | Set-Content $OutputPath -Encoding UTF8
        Write-Host "Session ledger written to: $OutputPath"
    } else {
        Write-Output $yaml
    }
}
finally {
    Pop-Location
}
