#!/usr/bin/env python3
"""QoderWork Task Runner — mandatory entry point for P0/P1 task execution.

Agents MUST use this runner instead of directly editing files.
The runner wraps the SADP pre-task enforcer at each boundary.

Usage:
  python scripts/qoderwork_task_runner.py start --task-id <ID>
  python scripts/qoderwork_task_runner.py edit-check --task-id <ID> --file <PATH>
  python scripts/qoderwork_task_runner.py finish --task-id <ID>

Exit codes:
  0 = PASS (proceed)
  1 = BLOCKED (SADP violation — do NOT proceed)
  2 = WARNING (advisory — may proceed with caution)

Workflow:
  1. Agent calls `start` before any file edits
  2. Agent calls `edit-check` before EACH file modification
  3. Agent calls `finish` after task completion (before reporting done)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Import the enforcer module
REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "scripts"
sys.path.insert(0, str(SCRIPTS))

import sadp_pre_task_enforcer as enforcer


def cmd_start(task_id: str) -> int:
    """Start a task — validates SADP compliance before editing begins.

    Checks:
    - TaskSpec exists with Gate 0 Ledger + Conflict Registry
    - No protected governance files in write_set
    - Acceptance gates defined

    Returns exit code (0=PASS, 1=BLOCKED, 2=WARNING).
    """
    print(f"=== SADP Task Runner: START {task_id} ===\n")

    exit_code, messages = enforcer.check_pre_task(task_id)

    for msg in messages:
        print(msg)

    if exit_code == 0:
        print(f"\n[PASS] Task {task_id} approved -- you may begin editing.")
        print(f"  Remember: call 'edit-check' before EACH file modification.")
    elif exit_code == 1:
        print(f"\n[BLOCKED] Task {task_id} BLOCKED -- do NOT edit any files.")
        print("  Fix the issues above and retry 'start'.")
    else:
        print(f"\n[WARNING] Task {task_id} has warnings -- review before proceeding.")

    return exit_code


def cmd_edit_check(task_id: str, file_path: str) -> int:
    """Check if a file edit is allowed under the current TaskSpec.

    Checks:
    - File is not a protected governance file
    - File is not a self-protecting enforcer file
    - File is in the TaskSpec's write_set
    - Priority-based scope creep blocking (P0/P1 → BLOCKED)

    Returns exit code (0=PASS, 1=BLOCKED, 2=WARNING).
    """
    print(f"=== SADP Task Runner: EDIT-CHECK {file_path} ===\n")

    exit_code, messages = enforcer.check_pre_edit(file_path, task_id)

    for msg in messages:
        print(msg)

    if exit_code == 0:
        print(f"\n[PASS] File {file_path} approved -- you may edit.")
    elif exit_code == 1:
        print(f"\n[BLOCKED] File {file_path} BLOCKED -- do NOT edit this file.")
        print("  If this file must be changed, update the TaskSpec write_set first.")
    else:
        print(f"\n[WARNING] File {file_path} has warnings -- review scope before editing.")

    return exit_code


def cmd_finish(task_id: str) -> int:
    """Finish a task — validates SADP compliance after completion.

    Checks:
    - ExecutionReport exists
    - Gate results documented
    - Reviewer Index exists (advisory)
    - Conflict Registry exists

    Returns exit code (0=PASS, 1=BLOCKED, 2=WARNING).
    """
    print(f"=== SADP Task Runner: FINISH {task_id} ===\n")

    exit_code, messages = enforcer.check_post_task(task_id)

    for msg in messages:
        print(msg)

    if exit_code == 0:
        print(f"\n[PASS] Task {task_id} completed -- all SADP artifacts present.")
        print("  You may now report completion to the reviewer.")
    elif exit_code == 1:
        print(f"\n[BLOCKED] Task {task_id} BLOCKED -- missing required artifacts.")
        print("  Create the missing artifacts before reporting completion.")
    else:
        print(f"\n[WARNING] Task {task_id} has advisories -- review before reporting.")

    return exit_code


def main() -> None:
    parser = argparse.ArgumentParser(
        description="QoderWork Task Runner — mandatory SADP entry point for P0/P1 tasks",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Workflow:
  1. python qoderwork_task_runner.py start --task-id <ID>
     Validates TaskSpec exists, Gate 0 valid, Conflict Registry declared.

  2. python qoderwork_task_runner.py edit-check --task-id <ID> --file <PATH>
     Validates file is in write_set, not protected, scope creep check.

  3. python qoderwork_task_runner.py finish --task-id <ID>
     Validates ExecutionReport, gate results, evidence artifacts.

Exit codes:
  0 = PASS (proceed)
  1 = BLOCKED (do NOT proceed)
  2 = WARNING (proceed with caution)
        """,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # start
    start_parser = subparsers.add_parser(
        "start", help="Start a task — validates SADP compliance before editing"
    )
    start_parser.add_argument(
        "--task-id", required=True, help="TaskSpec ID to start"
    )

    # edit-check
    edit_parser = subparsers.add_parser(
        "edit-check", help="Check if a file edit is allowed"
    )
    edit_parser.add_argument(
        "--task-id", required=True, help="Active TaskSpec ID"
    )
    edit_parser.add_argument(
        "--file", required=True, help="File path to check"
    )

    # finish
    finish_parser = subparsers.add_parser(
        "finish", help="Finish a task — validates completion artifacts"
    )
    finish_parser.add_argument(
        "--task-id", required=True, help="TaskSpec ID to finish"
    )

    args = parser.parse_args()

    if args.command == "start":
        sys.exit(cmd_start(args.task_id))
    elif args.command == "edit-check":
        sys.exit(cmd_edit_check(args.task_id, args.file))
    elif args.command == "finish":
        sys.exit(cmd_finish(args.task_id))
    else:
        parser.print_help()
        sys.exit(2)


if __name__ == "__main__":
    main()
